name: Node.js CI

# いつ実行するか
on:
  push:
    branches: [ "main", "js-ci-practice" ]
  pull_request:

# 何を実行するか
jobs:
  build:
    runs-on: ubuntu-latest # 最新のUbuntu環境で実行
    
    defaults:
      run:
        working-directory: ./ci-task

    steps:
    # 1. コードを取得
    - uses: actions/checkout@v4

    # 2. Node.js環境をセットアップ (バージョン20系を使用)
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. 依存ライブラリ(Jestなど)をインストール
    - name: Install dependencies
      run: npm install

    # 4. テストを実行
    - name: Run tests
      run: npm test